name: Python CI

# trigger the workflow on any push to the main branch or pull request 
on: 
  push:
    -main
  pull_request :
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1 : Check out the code from repository 
      - name: Check out code 
        uses: actions/checkout@v2
    
      # Step 2 : Setup python environment 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.0'
      
      #Step 3: Install all dependenices 
      - name: Install dependencies 
        run: |
          python -m pip install -- upgrade pip 
          pip install -r requirements.txt 
      
      #step 4: Run Test 
      - name: Run tests
        run: pytest
